# Generated by Django 5.2.7 on 2025-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
