# Generated by Django 5.2.7 on 2025-10-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Custommer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='custommer',
        ),
    ]
