# Generated by Django 5.2.7 on 2025-10-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0004_user_data_joined'),
        ('ecommerce', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custommer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth_users.userprofile'),
        ),
        migrations.DeleteModel(
            name='Custommer',
        ),
    ]
