# Generated by Django 5.2.7 on 2025-10-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_api_images/'),
        ),
    ]
