# Generated by Django 5.2.7 on 2025-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
