# Generated by Django 5.2.7 on 2025-10-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
