# Generated by Django 5.2.7 on 2025-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
