# Generated by Django 5.2.7 on 2025-10-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catagory', models.CharField(choices=[('FRTS', 'Frouts'), ('TY', 'Toy'), ('GR', 'Grosery')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='catatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_practice.catagory'),
        ),
    ]
