# Generated by Django 5.2.7 on 2025-10-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_practice', '0003_catagory_product_catatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='product_catagory',
            field=models.CharField(max_length=10),
        ),
    ]
